---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/TrailingWhitespace:
  Exclude:
    - spec/tic_tac_toe/board_spec.rb

Lint/UnusedMethodArgument:
  Enabled: false
